# Generated by Django 2.2.7 on 2019-11-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('camp', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
