# Generated by Django 2.2.7 on 2019-11-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_student_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
