# Generated by Django 2.2.7 on 2019-11-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='parent',
            name='work_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='work_mobile',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.Parent'),
        ),
    ]
