# Generated by Django 2.2.7 on 2019-11-26 11:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_auto_20191126_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/nimmy/PycharmProjects/camp/camp_reg/media'), upload_to=''),
        ),
    ]
