# Generated by Django 2.2.7 on 2019-11-26 19:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0012_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_card',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/Users/nimmy/PycharmProjects/camp/camp_reg/media'), upload_to=''),
        ),
    ]
